version: '3.9'

services:
  backend:
    build: ./backend
    container_name: tourisme-backend
    ports:
      - "4000:4000"
    volumes:
      - ./backend:/app
    environment:
      - PORT=4000
      - DB_HOST=db
      - DB_USER=postgres
      - DB_PASSWORD=postgres
      - DB_NAME=tourisme
    depends_on:
      - db

  frontend:
    build: ./frontend
    container_name: tourisme-frontend
    ports:
      - "3000:3000"
    volumes:
      - ./frontend:/app
    depends_on:
      - backend

  db:
    image: postgres:15
    container_name: tourisme-db
    ports:
      - "5432:5432"
    environment:
      POSTGRES_DB: tourisme
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: postgres
    volumes:
      - pgdata:/var/lib/postgresql/data

  redis:
    image: redis:alpine
    container_name: tourisme-redis
    ports:
      - "6379:6379"

volumes:
  pgdata:
